#---------------------------------------------------------------------
management:
  security:
    enabled: false

#---------------------------------------------------------------------
spring:
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false 
    spring.h2.console.settings.web-allow-others: false
  datasource:
#    url: jdbc:h2:mem:mydb
    url: jdbc:h2:file:/Project/EclipsecSTS/PilotAutomationServer/h2data
    username: sa
    password: password
    driverClassName: org.h2.Driver
#    hikari:
#     maximum-pool-size: 15
#     minimum-idle: 15
#     auto-commit: true
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: create #update #none #create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: pilotautomation
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog/liquibase-changeLogH2.xml
  devtools:
    add-properties: true
    livereload: 
      enabled: true
      port: 35729
    remote.restart.enabled: true
    
    
#---------------------------------------------------------------------
server:
  host: locahost
  port: 8443
  
#---------------------------------------------------------------------
#springfox:
#  documentation:
#    swagger:
#      v2:
#        path: /api-docs

#---------------------------------------------------------------------
